language: 'node_js'
node_js: '10'

# Script that is run before the script phase
before_script:
- npm run build-storybook
# Remove this line when we add in tests
script:
- echo "Currently there are no tests, skipping"
# Deployment information
deploy:
  provider: pages 
  skip-cleanup: true 
  github-token: $GITHUB_TOKEN 
  local_dir: storybook-static 
  repo: GovTechSG/sgds-govtech-react 
  target_branch: gh-pages 
  on:
    branch: master 
